disabled_rules:
- trailing_whitespace

opt_in_rules:
- attributes
- closure_spacing
- empty_count
- explicit_init
- fatal_error_message
- first_where
- operator_usage_whitespace
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- switch_case_on_newline
- valid_docs

excluded:
- Pods/
- Carthage/
- vendor/
- R.generated.swift

line_length: 300

identifier_name:
  min_length: 2
