language: objective-c
osx_image: xcode10.1

cache:
  directories:
  - Carthage
  - vendor/bundle
  
install:
  - brew install swiftlint
  - gem update bundler --no-ri --no-rdoc --no-document
  - bundle install --without production --deployment
  
script: 
  - bundle exec fastlane lint
  - bundle exec fastlane test
