default_platform(:ios)

platform :ios do

  desc "setup library"
  lane :setup_library do
    cocoapods
    carthage(platform: 'ios', cache_builds: true)
  end
  
  desc "check code format"
  lane :check_code do
    danger
  end
  
  desc "exec test"
  lane :test do
    cocoapods
    carthage(platform: 'ios', cache_builds: true)
    run_tests(device: 'iPhone X')
  end
end
