default_platform(:ios)

platform :ios do

  desc "setup library"
  lane :setup_library do 
    carthage
  end
  
  desc "check code format"
  lane :check_code do
    swiftlint
    danger
  end
  
  desc "exec test"
  lane :test do
    danger
    carthage(platform: 'ios', cache_builds: true)
    run_tests
  end
end
